### PR TITLE
Removing Releases and _alternatives folder

### PR DESCRIPTION
**Pull request by theypsilon**
Releases folder was redundant, as releases is present.
And _alternatives are now in the MRA-Alternatives_MiSTer repository.

### CODE REVIEW

**Comment by sorgelig** [comment]
Why you should remove releases? 
That's not correct.

**Comment by theypsilon** [comment]
@sorgelig  There are two folders in this repository. `Releases` with upper case letter and `releases` with lower case letter. Both folders contain the same, they are just duplicated. This PR deletes the folder with upper case first letter.

**Comment by sorgelig** [comment]
i see

**Comment by theypsilon** [comment]
This has been done already

**Pull request closed without merging**
